# Generated by Django 2.2.1 on 2019-06-12 06:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='raw_files')),
                ('request_type', models.IntegerField(default=0)),
                ('ip', models.CharField(max_length=30)),
                ('model_type', models.IntegerField(default=0)),
                ('tmp_code', models.CharField(blank=True, max_length=512, null=True)),
                ('ret', models.FileField(blank=True, null=True, upload_to='results')),
                ('finish_flag', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.Profile')),
            ],
        ),
    ]
