# Generated by Django 2.2.1 on 2019-06-13 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textfile',
            old_name='author',
            new_name='profile',
        ),
    ]
