# Generated by Django 2.2.1 on 2019-06-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_auto_20190613_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='file',
            field=models.FileField(upload_to='text_files'),
        ),
    ]
