# Generated by Django 2.2.1 on 2019-06-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0003_auto_20190613_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='return_text',
            field=models.FileField(blank=True, null=True, upload_to='return_files'),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='ip',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
