# Generated by Django 2.2.1 on 2019-06-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='files_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='finished_num',
            field=models.IntegerField(default=0),
        ),
    ]
