# Generated by Django 2.2.1 on 2019-06-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_rawfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rawfile',
        ),
    ]
